# fly.toml app configuration file generated for modible2 on 2024-09-05T22:16:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "modible2"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
